apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jmeter
        company: PingIdentity
      name: jmeter
    spec:
      containers:
      - env:
          - name: SERVER_PROFILE_URL
            value: https://github.com/ping-devops-program/anydevops
          - name: SERVER_PROFILE_PATH
            value: now/profile/jmeter
          - name: STARTUP_FOREGROUND_OPTS
            value: --nongui -t /opt/out/instance/bin/authorization_code.jmx -JthreadCount=1 -Jduration=1000
        image: pingidentity/apache-jmeter:edge
        imagePullPolicy: Always
        name: jmeter
        ports:
        - containerPort: 1099
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi